name: Deploy Static Website to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Updated region to N. Virginia
    
    - name: Build Docker Image
      run: |
        docker build -t static-website .
    
    - name: Deploy to S3
      run: |
        aws s3 sync ./src/ s3://hina-atif-static-website/ --delete
        aws s3 website s3://hina-atif-static-website/ --index-document index.html --error-document error.html
